# experimental setup
N: 31
K: 5
# dataset specific
dataset: "office31"
subdomain_id: 0 # domain id of server pretraining
dataset_path: "data/"

# model setup
net: "resnet50"
adaptation_type: "end_2_end"
optimizer: "sgd"

# hardware - change to gpu/cpu if required
accelerator: "gpu"
devices: "1"

# federated training configuration
pretrain: "True"
fast_dev_run: "False"
fast_server_startup: "True"
num_workers: 4
batch_size_train: 128
batch_size_test: 64
num_rounds: 1
min_fit_clients: 2
min_available_clients: 2
min_eval_clients: 2
max_epochs: 300
log_every_n_steps: 1
precision: 16
check_val_every_n_epoch: 10
host_address: "localhost:8080"

# debugging/memory tracking
#profiler: "pytorch"
log_gpu_memory: "all"
#track_grad_norm: "2"
# requires patch to work on windows, remove dtype conversion in summary.py
log_parameters: "0"