N: 31
K: 5
dataset: "office31"
net: "resnet34"
fast_dev_run: "False"
fast_server_startup: "True"
num_workers: 4
dataset_path: "data/"
batch_size_train: 128
batch_size_test: 64
pretrain: "False"
num_rounds: 3
min_fit_clients: 1
min_available_clients: 1
min_eval_clients: 1
accelerator: "gpu"
devices: "1"
max_epochs: 100
log_every_n_steps: 1
adaptation_type: "end_2_end"
precision: 16
check_val_every_n_epoch: 5